export const skillList = [
  { id: "firebase", value: "firebase" },
  { id: "React", value: "react" },
  { id: "React Native", value: "react" },
  { id: "kotlin", value: "kotlin" },
  { id: "JetpackCompose", value: "jetpackcompose" },
  { id: "Next.js", value: "nextdotjs" },
  { id: "Nuxt.js", value: "nuxtdotjs" },
  { id: "NestJS", value: "nestjs" },
  { id: "Vue.js", value: "vuedotjs" },
  { id: "Node.js", value: "nodedotjs" },
  { id: "Three.js", value: "threedotjs" },
  { id: "AngularJS", value: "angularjs" },
  { id: "JavaScript", value: "javascript" },
  { id: "TypeScript", value: "typescript" },
  { id: "Python", value: "python" },
  { id: "PHP", value: "php" },
  { id: "Pug", value: "pug" },
  { id: "Recoil", value: "recoil" },
  { id: "Redux", value: "redux" },
  { id: "Prisma", value: "prisma" },
  { id: "sass", value: "sass" },
  { id: "Tailwind CSS", value: "tailwindcss" },
  { id: "styled components", value: "styledcomponents" },
  { id: "Ruby", value: "ruby" },
  { id: "Socket.io", value: "socketdotio" },
  { id: "Spring", value: "spring" },
  { id: "Spring Boot", value: "springboot" },
  { id: "Vitess", value: "vitess" },
  { id: "Oracle", value: "oracle" },
  { id: "OpenAI", value: "openai" },
  { id: "Gatsby", value: "gatsby" },
  { id: "MySQL", value: "mysql" },
  { id: "PostgresSQL", value: "postgresql" },
  { id: "MongoDB", value: "mongodb" },
  { id: "MariaDB", value: "mariadb" },
  { id: "jQuery", value: "jquery" },
  { id: "Jest", value: "jest" },
  { id: "flutter", value: "flutter" },
  { id: "Dart", value: "dart" },
  { id: "C", value: "c" },
  { id: "C#", value: "csharp" },
  { id: "C++", value: "cplusplus" },
  { id: "Amazon RDS", value: "amazonrds" },
  { id: "Amazon EC2", value: "amazonec2" },
];

export const categoryList = ["JAVA", "Python", "C", "C++"];

export const popularSkills = [
  "javascript",
  "React",
  "Github",
  "typescript",
  "css",
  "Java",
  "html",
  "Next.js",
  "MySQL",
  "python",
  "html5",
  "Node.js",
  "UI 디자인",
  "SpringBoot",
  "css3",
  "커뮤니케이션",
  "UX 디자인",
  "AWS",
  "Vue.js",
  "c언어",
  "Android",
  "React Query",
  "C++",
  "React Native",
  "Flutter",
  "c#",
  "Kotlin",
  "swift",
  "iOS",
  "Unity",
];

export const industryList = [
  { id: "industry-checkbox-1", label: "B2B" },
  { id: "industry-checkbox-2", label: "SaaS" },
  { id: "industry-checkbox-3", label: "플랫폼" },
  { id: "industry-checkbox-4", label: "이커머스" },
  { id: "industry-checkbox-5", label: "커뮤니티 / 소셜네트워킹" },
  { id: "industry-checkbox-6", label: "HR" },
  { id: "industry-checkbox-7", label: "금융 / 핀테크" },
  { id: "industry-checkbox-8", label: "교육 / 에듀테크" },
  { id: "industry-checkbox-9", label: "여행" },
  { id: "industry-checkbox-10", label: "콘텐츠" },
  { id: "industry-checkbox-11", label: "라이프스타일" },
  { id: "industry-checkbox-12", label: "의료 / 헬스케어" },
  { id: "industry-checkbox-13", label: "패션 / 뷰티" },
  { id: "industry-checkbox-14", label: "블록체인" },
  { id: "industry-checkbox-15", label: "AI" },
  { id: "industry-checkbox-16", label: "모빌리티 / 교통" },
  { id: "industry-checkbox-17", label: "게임" },
  { id: "industry-checkbox-18", label: "식음료" },
  { id: "industry-checkbox-19", label: "반려동물" },
  { id: "industry-checkbox-20", label: "유아" },
  { id: "industry-checkbox-21", label: "스포츠" },
  { id: "industry-checkbox-22", label: "법률" },
  { id: "industry-checkbox-23", label: "광고 / 마케팅" },
  { id: "industry-checkbox-24", label: "주거 / 부동산 / 프롭테크" },
  { id: "industry-checkbox-25", label: "보안" },
  { id: "industry-checkbox-26", label: "제조" },
  { id: "industry-checkbox-27", label: "방송 / 엔터테인먼트" },
  { id: "industry-checkbox-28", label: "농축수산업 / 애그테크" },
  { id: "industry-checkbox-29", label: "전자제품" },
  { id: "industry-checkbox-30", label: "정부 / 공공" },
  { id: "industry-checkbox-31", label: "건설" },
  { id: "industry-checkbox-32", label: "환경 / 에너지" },
  { id: "industry-checkbox-33", label: "물류 / 유통" },
  { id: "industry-checkbox-34", label: "반도체" },
  { id: "industry-checkbox-35", label: "컨설팅" },
];

export const topics = [
  "react",
  "java",
  "프론트엔드",
  "백엔드",
  "취업",
  "spring",
  "javascript",
  "비전공자",
  "신입",
  "이직",
  "python",
  "next.js",
  "인공지능",
  "포트폴리오",
  "부트캠프",
  "node.js",
  "react-native",
  "ios",
  "flutter",
  "연봉",
];
export const tags = [
  "javascript",
  "react",
  "java",
  "spring",
  "python",
  "ai",
  "프론트엔드",
  "백엔드",
  "비전공자",
  "이직",
];
