
export const skillList = [
  { id: "firebase", value: "firebase" },
  { id: "React", value: "react" },
  { id: "React Native", value: "react" },
  { id: "kotlin", value: "kotlin" },
  { id: "JetpackCompose", value: "jetpackcompose" },
  { id: "Next.js", value: "nextdotjs" },
  { id: "Nuxt.js", value: "nuxtdotjs" },
  { id: "NestJS", value: "nestjs" },
  { id: "Vue.js", value: "vuedotjs" },
  { id: "Node.js", value: "nodedotjs" },
  { id: "Three.js", value: "threedotjs" },
  { id: "AngularJS", value: "angularjs" },
  { id: "JavaScript", value: "javascript" },
  { id: "TypeScript", value: "typescript" },
  { id: "Python", value: "python" },
  { id: "PHP", value: "php" },
  { id: "Pug", value: "pug" },
  { id: "Recoil", value: "recoil" },
  { id: "Redux", value: "redux" },
  { id: "Prisma", value: "prisma" },
  { id: "sass", value: "sass" },
  { id: "Tailwind CSS", value: "tailwindcss" },
  { id: "styled components", value: "styledcomponents" },
  { id: "Ruby", value: "ruby" },
  { id: "Socket.io", value: "socketdotio" },
  { id: "Spring", value: "spring" },
  { id: "Spring Boot", value: "springboot" },
  { id: "Vitess", value: "vitess" },
  { id: "Oracle", value: "oracle" },
  { id: "OpenAI", value: "openai" },
  { id: "Gatsby", value: "gatsby" },
  { id: "MySQL", value: "mysql" },
  { id: "PostgresSQL", value: "postgresql" },
  { id: "MongoDB", value: "mongodb" },
  { id: "MariaDB", value: "mariadb" },
  { id: "jQuery", value: "jquery" },
  { id: "Jest", value: "jest" },
  { id: "flutter", value: "flutter" },
  { id: "Dart", value: "dart" },
  { id: "C", value: "c" },
  { id: "C#", value: "csharp" },
  { id: "C++", value: "cplusplus" },
  { id: "Amazon RDS", value: "amazonrds" },
  { id: "Amazon EC2", value: "amazonec2" },
];

export const categoryList = ['JAVA', 'Python', 'C', 'C++']